### ISSUE TITLE
the MK64FN1M0Vxx12 needs to be added as a multipart component

### ISSUE THREAD

**Issue by odinthenerd** [auto-intern/ai_kicad#1]
You can see two parts of it here:

https://github.com/auto-intern/aiPowerProbe_PCB/blob/master/EMV1/Network.xps

Its simply too many pins to be one component in my opinion. Is this possible with KiCad?

**Comment by CvRXX** [comment]
Oke, I found the solution. It is quite weird but works well. The steps you have to take:

1. Add a new symbol with the amount of parts you want.
2. Draw a rectangle
3. Right click the rectangle and click edit rectangle options
4. Deselect all sharing options
5. Remove rectangle 
6. You can now edit every part without modifying the others

I hope this works for you.

**Comment by CvRXX** [comment]
[Added](https://github.com/auto-intern/ai_kicad/commit/04c7e903508ad613346f37c1d4f5d3bbca444307)
